site_name: "InvoiceJet — Dokumentacja Użytkownika"
site_description: "Przewodnik użytkownika aplikacji InvoiceJet"
site_url: "http://127.0.0.1:8002/"
docs_dir: "G:\\Projekty informatyczne\\Gotowe aplikacje\\InvoiceJet\\InvoiceJet\\doc_user"
site_dir: "_site"
use_directory_urls: false

theme:
  name: material
  language: pl
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Tryb ciemny
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Tryb jasny
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - navigation.footer
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy

edit_uri: ""

plugins:
  - search:
      lang: pl
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
